# Generated by Django 5.2.15 on 2026-06-17 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('Resume', 'Resume'), ('Offer Letter', 'Offer Letter'), ('Contract', 'Contract'), ('Certificate', 'Certificate'), ('Government ID', 'Government ID'), ('Other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='employee_docs/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
